### ISSUE TITLE
test failures: unorderable types: Edge() < Edge()

### ISSUE THREAD

**Issue by rekado** [jeetsukumaran/DendroPy#77]
I'm seeing two test failures in DendroPy 4.2.0.

~~~
======================================================================
ERROR: test_fixed_species_tree_fitting (dendropy.test.test_multispeciescoalescent.MultispeciesCoalescentBasicTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/tmp/guix-build-python-dendropy-4.2.0.drv-0/DendroPy-4.2.0/dendropy/test/test_multispeciescoalescent.py", line 189, in test_fixed_species_tree_fitting
    coalescent_species_lineage_map_fn=lambda x: coalescent_to_species_taxon_map[x])
  File "/tmp/guix-build-python-dendropy-4.2.0.drv-0/DendroPy-4.2.0/dendropy/model/multispeciescoalescent.py", line 244, in _fit_coalescent_tree
    heapq.heapify(current_lineages)
TypeError: unorderable types: Edge() < Edge()

======================================================================
ERROR: test1 (dendropy.test.test_multispeciescoalescent.MultispeciesCoalescentFixedSingleTreesCalculationTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/tmp/guix-build-python-dendropy-4.2.0.drv-0/DendroPy-4.2.0/dendropy/test/test_multispeciescoalescent.py", line 118, in test1
    coalescent_species_lineage_map_fn=coalescent_species_lineage_map_fn,
  File "/tmp/guix-build-python-dendropy-4.2.0.drv-0/DendroPy-4.2.0/dendropy/model/multispeciescoalescent.py", line 116, in score_coalescent_tree
    is_coalescent_species_lineage_map_by_node=is_coalescent_species_lineage_map_by_node)
  File "/tmp/guix-build-python-dendropy-4.2.0.drv-0/DendroPy-4.2.0/dendropy/model/multispeciescoalescent.py", line 244, in _fit_coalescent_tree
    heapq.heapify(current_lineages)
TypeError: unorderable types: Edge() < Edge()
~~~

**Comment by jeetsukumaran** [comment]
Thanks for pointing this out. This has been fixed in: 93f984b .
