### ISSUE TITLE
popgenstat behavior is strange

### ISSUE THREAD

**Issue by tiagoantao** [jeetsukumaran/DendroPy#93]
I might be doing something quite stupid here, but it seems that popgenstat is returning strange results:

```python
import dendropy
from dendropy.calculate import popgenstat
cm = dendropy.DnaCharacterMatrix()
cm.from_dict({'a': 'AT', 'b': AA})
popgenstat.num_segregating_sites(cm)
```

This returns

```python
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/tiago_antao/anaconda3/lib/python3.6/site-packages/DendroPy-4.2.0-py3.6.egg/dendropy/calculate/popgenstat.py", line 171, in num_segregating_sites
    ignore_uncertain)
  File "/home/tiago_antao/anaconda3/lib/python3.6/site-packages/DendroPy-4.2.0-py3.6.egg/dendropy/calculate/popgenstat.py", line 116, in _num_segregating_sites
    for i, c1 in enumerate(char_sequences[0]):
IndexError: list index out of range
```

Am I forgetting something obvious?

**Comment by tiagoantao** [comment]
ping @martavohnoutova

**Comment by jeetsukumaran** [comment]
Hi @tiagoantao 

This may be poor documentation on our part, but ``from_dict`` is actually a factory function that returns a DnaCharacterMatrix, rather than a method to populate an existing character matrix. So, your code should look more like this:
~~~
#! /usr/bin/env python
# -*- coding: utf-8 -*-
import dendropy
from dendropy.calculate import popgenstat
cm = dendropy.DnaCharacterMatrix.from_dict({'a': 'AT', 'b': "AA"})
popgenstat.num_segregating_sites(cm)
~~~

**Comment by tiagoantao** [comment]
No, the documentation is correct.

I am an idiot and should have read more carefully. Sorry
